### ISSUE TITLE
TextEdit Widget

### ISSUE THREAD

**Issue by henriiquecampos** [pigdevstudio/kitchen-tales#1]
# Description

Add a small widget that can be called during the tutorial to show the code behind a recipe.

![10](https://user-images.githubusercontent.com/10171059/43090418-a729799c-8e7d-11e8-8c04-059d11a6e134.png)

The widget is meant to mimic the Godot Script editor, highlighting `GDScript` syntax.

It also needs a `CopyButton` which will copy the content of the `TextEdit` to the clipboard of the user.

And to maintain the **animation** feeling of the episode, the widget also need a way to animate the text inside of it, just like we can do with `Label.percent_visible` and `Label.visible_characters`, with these properties being exposed (through `export var`) to the `Editor` so we can insert their values as keyframes for `Animations` with `AnimationPlayer`.

It also need a way to hide some of the lines of its code, meaning that https://github.com/godotengine/godot/issues/19981 will probably have to either be fixed or to be workaround. So something like `Label.max_lines_visible` and `Label.lines_skipped` is close to what is needed. ¯\＿(ツ)＿/¯

## Resume

- A `TextEdit` that highlights Godot's API just like Godot's Script Editor
- It needs `Label.perfenct_visible` and `Label.visible_characters` like features
- Users, through a button, can copy the visible text to their clipboard
 
## Todo
- [x] Godot API highlight
- [ ] TextEdit.percent_visible
- [ ] TextEdit.visible_characters
- [ ] TextEdit.lines_skipped
- [ ] TextEdit.max_lines_visible

**Comment by henriiquecampos** [comment]
This shall be moved to the Kitchen Tales Show repository, this one is for the game.
